### PR TITLE
WRS-3590 Fix indexing configuration

### PR DESCRIPTION
**Pull request by e5l**
Fix [WRS-3590](https://youtrack.jetbrains.com/issue/WRS-3590) ktor.io/docs website doesn't appear in google search

### CODE REVIEW

**Review by vnikolova — APPROVED** [review]
:+1:

**Comment by e5l** [comment]
@vnikolova, could you please deploy the new version with this change?

**Comment by vnikolova** [comment]
@e5l absolutely, I am on it!

**Comment by vnikolova** [comment]
@e5l the changes are now deployed to prod.

**Comment by e5l** [comment]
Thank you!

**Pull request merged**
