### PR TITLE
Fix: KTOR-7248 Methods in FakeTaskRepository in first iteration shouldn't have the suspend keyword

### PR DESCRIPTION
**Pull request by Omasyo**
[KTOR-7248](https://youtrack.jetbrains.com/issue/KTOR-7248)

In this tutorial: https://ktor.io/docs/server-integrate-database.html#add-starter-code.

The TaskRepository interface does not match the sample code, it is missing the suspend keyword. I have fixed this.

### CODE REVIEW

**Comment by vnikolova** [comment]
Thanks for picking this up @Omasyo. 

I had a look at the issue and it seems like there's been a mistake. It's not the `TaskRepository`, but the `FakeTaskRepository` in the next step that needs to be corrected. I updated the YT issue with the correct code snippet and updated description.

So, instead of referencing the code from the final example, we need to paste this part directly into the `<code-block>` element. Can you revert your changes and do this instead?

**Comment by Omasyo** [comment]
Okay I'll do that

**Comment by Omasyo** [comment]
How about this @vnikolova

**Review by vnikolova — APPROVED** [review]
Looks good, thanks for the update!

**Pull request merged**
