### PR TITLE
KTOR-6499 Document changes in Environment,Engine, Application

### PR DESCRIPTION
**Pull request by vnikolova**
[KTOR-6499](https://youtrack.jetbrains.com/issue/KTOR-6499/Documentation-for-Environment-Engine-Application-Design)

[Preview on staging](https://writerside.labs.jb.gg/staging/staging/ktor/3.0.0/migrating-3.html#applicationengine-applicationenvironment-and-application)

- [x] update code samples
- [x] update code snippet line references
- [x] update links pointing from `ktor-host-common` module to `ktor-server-core`
- [x] fix formatting
- [x] document changes in the migration guide 
    - added subsection "ApplicationEngine, ApplicationEnvironment, and Application﻿"
    - added subsection "ktor-server-host-common module has been removed"

### CODE REVIEW

**Review by e5l — APPROVED** [review]
it would be great to have side by side view for versions, like diff

**Comment by vnikolova** [comment]
> it would be great to have side by side view for versions, like diff

@e5l Agreed. I can add some table views, such as for the renamed classes and imports.

**Comment by e5l** [comment]
It would be great. Btw could you tell me if we have diff component for docs?

**Comment by vnikolova** [comment]
Actually, I just found there's a [`compare` element](https://www.jetbrains.com/help/writerside/code-blocks-semantic.html#compare-two-code-blocks) for code blocks. We can use it instead of tabs.

**Pull request merged**
